# Generated by Django 3.1.7 on 2021-04-19 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_users_list', 'Can view the list of users')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
    ]
