# Generated by Django 3.1.7 on 2021-04-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210421_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='github',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='Github'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='About'),
        ),
    ]
