# Generated by Django 3.1.7 on 2021-03-11 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('in_progress', 'In progress'), ('done', 'Done')], max_length=11, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('t', 'Task'), ('b', 'Bug'), ('e', 'Enhancement')], max_length=11, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300, verbose_name='Title')),
                ('description', models.TextField(max_length=3000, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tstatuses', to='webapp.status', verbose_name='Status')),
                ('task_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='types', to='webapp.type', verbose_name='Type')),
            ],
        ),
    ]
