# Generated by Django 3.1.7 on 2021-03-15 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20210311_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status_new',
            field=models.ManyToManyField(related_name='statuses', to='webapp.Status', verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type_new',
            field=models.ManyToManyField(related_name='types', to='webapp.Type', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_statuses', to='webapp.status', verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_types', to='webapp.type', verbose_name='Type'),
        ),
    ]
