# Generated by Django 3.1.7 on 2021-03-15 09:17

from django.db import migrations

def transfer_types(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.task_type_new.set([task.task_type.id])



def rollback_transfer(apps, schema_editor):
    Task = apps.get_model('webapp.Task')
    for task in Task.objects.all():
        task.task_type.set(task.task_type_new.first())


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20210315_0915'),
    ]

    operations = [
        migrations.RunPython(transfer_types, rollback_transfer)
    ]
