# Generated by Django 3.1.7 on 2021-03-15 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_task_task_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_type_new',
            new_name='task_type',
        ),
    ]
