# Generated by Django 3.1.7 on 2021-03-18 12:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20210315_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(1000)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=300, validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(1000)], verbose_name='Title'),
        ),
    ]
