# Generated by Django 3.1.7 on 2021-03-18 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_auto_20210318_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=300, validators=[django.core.validators.MaxLengthValidator(20)], verbose_name='Title'),
        ),
    ]
