# Generated by Django 3.1.7 on 2021-03-29 09:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20210318_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
                ('project_name', models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15)], verbose_name='Title')),
                ('project_description', models.TextField(max_length=3000, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.AlterField(
            model_name='task',
            name='summary',
            field=models.CharField(max_length=15, validators=[django.core.validators.MaxLengthValidator(15)], verbose_name='Title'),
        ),
    ]
