# Generated by Django 3.1.7 on 2021-04-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_auto_20210415_0947'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': [('user_list_change', 'Can change the list of users of the project')], 'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
    ]
